#!/bin/bash

PURPLE=$'\e[1;35m'
RESET=$'\e[0m'

echo "
${PURPLE}
 ██████╗ ███████╗███╗   ███╗ ██████╗ ███████╗██╗███████╗
██╔═══██╗██╔════╝████╗ ████║██╔═══██╗██╔════╝██║██╔════╝
██║   ██║███████╗██╔████╔██║██║   ██║███████╗██║███████╗
██║   ██║╚════██║██║╚██╔╝██║██║   ██║╚════██║██║╚════██║
╚██████╔╝███████║██║ ╚═╝ ██║╚██████╔╝███████║██║███████║
 ╚═════╝ ╚══════╝╚═╝     ╚═╝ ╚═════╝ ╚══════╝╚═╝╚══════╝
 ${RESET}
For documentation visit: ${PURPLE}http://docs.osmosis.zone/ ${RESET}

To sync this node on mainnet run: 
    ${PURPLE}/root/start.sh ${RESET}

To sync this node on testnet run: 
    ${PURPLE}/root/start.sh osmo-test-5 ${RESET}

For all other setups, please run osmosis installer:
    ${PURPLE}source <(curl -sL https://get.osmosis.zone/run) ${RESET}

********************************************************************************
To delete this message: rm -rf $(readlink -f ${0})
"